### ISSUE TITLE
StaticMathField does not render properly

### ISSUE THREAD

**Issue by joaortizro** [viktorstrate/react-mathquill#10]
Hi,
This is a completely new react project, so no other dependencies .I just did a quick test according to the instructions.

![image](https://user-images.githubusercontent.com/20843665/73203014-3f8e7300-410a-11ea-9ee9-09b984098e93.png)

this is the code just in case

![image](https://user-images.githubusercontent.com/20843665/73203043-4ddc8f00-410a-11ea-8017-049b708830e0.png)

**Comment by viktorstrate** [comment]
Looks right, I will look into it.

**Comment by viktorstrate** [comment]
This should be solved in v0.2.1, that i've just pushed.
Please reopen the issue, if the problem persists
