### ISSUE TITLE
Allow changing the mathquill value externally?

### ISSUE THREAD

**Issue by jmeyers91** [viktorstrate/react-mathquill#11]
Currently it looks like the component only binds the `latex` prop on mount, but that means if anything other than the user changes the value, the mathquill instance won't get updated. There should be a check in `componentDidUpdate` that calls `mathField.latex(newValue)` if a new `latex` value is passed in. I can make a PR for this if you'd like.

**Comment by viktorstrate** [comment]
Thank you for opening the issue.
I would appreciate if you sent a pull request :)

**Comment by viktorstrate** [comment]
Fixed in pull request #12
