### ISSUE TITLE
Add MathField.text() method to interface

### ISSUE THREAD

**Issue by mark-wiemer** [viktorstrate/react-mathquill#13]
I'm trying to copy your example in TypeScript, but I'm getting an error when I try to call [`mathField.text()`](https://github.com/viktorstrate/react-mathquill/blob/master/examples/src/EditableMathExample.js#L34): `Property 'text' does not exist on type 'MathField'. ts(2239)`. I'm pretty sure this can be fixed by adding the property to [`index.d.ts`](https://github.com/viktorstrate/react-mathquill/blob/master/index.d.ts#L59), but I'm not an expert.

My current fix is using `(mathField as any).text()`.

**Comment by viktorstrate** [comment]
I only recently added the type definitions, so they might be missing some properties. Well spotted.

I have added the property to `index.d.ts`, and pushed it to version 0.2.4.
If it still doesn't work, please reopen the issue.

**Comment by mark-wiemer** [comment]
It works, thanks!
