### ISSUE TITLE
Focus MathQuill field programmatically

### ISSUE THREAD

**Issue by gigincg** [viktorstrate/react-mathquill#18]
Is there any way to programatically focus the EditableMathField?

**Comment by viktorstrate** [comment]
Yes, you can get a handle on the mathquill object itself with the `mathquillDidMount` prop.

Somthing like this, though you would probably want to save `mathField` to a class variable (or with useRef) so it can be used whenever:

```javascript
const CustomMathquill = () => {
  return (
    <EditableMathField
        mathquillDidMount={mathField => {
          mathField.focus()
        }}
      />
  )
}
```
