### ISSUE TITLE
EditableMathField not allowing reset state

### ISSUE THREAD

**Issue by gbedad** [viktorstrate/react-mathquill#22]
I am using a react component with <EditableMathField onChange={handleChange}/>. The equation is updated but when I can't reset the state to initial state after the first input.
A) Input ans
<EditableMathField className="mathInput" onChange={handleChange} />

B) Manage handleChange
  const handleChange = (mathField) => {
    setAns(mathField.latex());
    setText(mathField.text());

    console.log('text changed:', text);
    console.log('ans changed:', ans);
  };

I try to reset with following function :
const handleRefresh = () => {
    setRandA(parseInt(Math.random() * 6 + 1));
    setRandB(parseInt(Math.random() * 6 + 1));
    setRandC(parseInt(Math.random() * 6 + 1));
    setRandD(parseInt(Math.random() * 6 + 1));
    const newAns = '';
    setAns(toTex(newAns));

    setText('');
    setColorButton('#425198');

    console.log('ans reseted', ans);
    console.log('text reseted', text);
  };
I can follow the state of the ans by setAns(null) in react developer tool and it is updated correctly but the input zone in editableMathField is not changing.
Thank you in advance for the support

Gerald

**Comment by viktorstrate** [comment]
Sorry for the late response, I haven't been at my computer for a while :)
I'm not sure if this is what you mean, but I've provided an example of resetting the field to some initial state.

You can play with it here https://codesandbox.io/s/damp-cdn-0jdj0?file=/src/App.js

```javascript
const MyMathComponent = () => {

  const initialLatex = 'e = m c^2'
  const [mathState, setMathState] = useState(initialLatex)

  return (
    <div>
      <EditableMathField
          latex={mathState}
          onChange={(mathField) => {
            setMathState( mathField.latex() )
          }}
        />
      <button onClick={ () => { setMathState(initialLatex) } }>
        Reset
      </button>
    </div>
  )
}
```

**Comment by gbedad** [comment]
Hi Viktor, Thank you so much for your reply. It works perfectly. I just set the initialLatex to ‘ ‘. I am developing an app for teaching maths to teens between 11 and 15. Do you mind if I contact you again in case of problems. Regards Gerald Provenance : Courrier pour Windows 10 De : Viktor Strate KløvedalEnvoyé le :lundi 27 juillet 2020 17:04À : viktorstrate/react-mathquillCc : Gerald; AuthorObjet :Re: [viktorstrate/react-mathquill] EditableMathField not allowing reset state (#22) Sorry for the late response, I haven't been at my computer for a while :)I'm not sure if this is what you mean, but I've provided an example of resetting the field to some initial state.You can play with it here https://codesandbox.io/s/damp-cdn-0jdj0?file=/src/App.jsconst MyMathComponent = () => {   const initialLatex = 'e = m c^2'  const [mathState, setMathState] = useState(initialLatex)   return (    <div>      <EditableMathField          latex={mathState}          onChange={(mathField) => {            setMathState( mathField.latex() )          }}        />      <button onClick={ () => { setMathState(initialLatex) } }>        Reset      </button>    </div>  )}—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by viktorstrate** [comment]
Awesome! If you have other questions you shall be welcome to contact me at viktorstrate@gmail.com
