### ISSUE TITLE
Possible for EditableMathField to be compatible with selectionStart?

### ISSUE THREAD

**Issue by timkinsman** [viktorstrate/react-mathquill#26]
When EditableMathField is triggered by onKeyUp={(e) => console.log(e.target.selectionStart)} it always returns 0 no matter the position of the cursor. Is there a possible work around to retrieve the cursor position? Thanks.

**Comment by viktorstrate** [comment]
I don't think it is possible to get information about the selection in MathQuill, at least not with the public API.
You can however change or clear the selection, [see the docs](https://docs.mathquill.com/en/latest/Api_Methods/#select).

As your issue doesn't clearly relate to the react wrapper around the real [MathQuill library](http://mathquill.com/),
you should istead seek help over at their repository.

I did find this issue similar, but it hasn't been solved yet mathquill/mathquill/issues/908.
