### ISSUE TITLE
Displayin math functions using react-mathquill

### ISSUE THREAD

**Issue by Slimaneel** [viktorstrate/react-mathquill#27]
I am trying to display math functions in the input field by clicking on the button of the corresponding function. However, rather than having the functions merge to create one equation like this cos(√). each equation is added to the right of the one already displayed. Example: cos() √

Here is the code that I am using: 

import React, {useState} from 'react'
import { addStyles, EditableMathField  } from 'react-mathquill'

addStyles();

function App(props) {
  const [latex, setLatex] = useState("");
  const injectMathFunction = (latexString) => {
    setLatex((latex) => latex + latexString);
  };
  return (
    <div>
      <EditableMathField
        latex={latex} // latex value for the input field
        onChange={(mathField) => {
          
          setLatex(mathField.latex());
        }}
      />
      <button onClick={() => injectMathFunction("{\\sqrt{}}")}>√</button>
     <button  onClick={() => injectMathFunction("\\cos")}>cos</button>

    </div>
  );
}

Thanks a lot!

**Comment by viktorstrate** [comment]
In the `injectMathFunction`, you just append the `latexString` to the current latex, which results in the `√` just being appended.
I think what you are looking for is the `mathField.cmd(latex_string)` function.

Something like:
```javascript
<EditableMathField
    latex={latex}
    onChange={ mathField => mathField.cmd('\\sqrt') } />
```
