### ISSUE TITLE
Trigger Mathfield.cmd on onClick function

### ISSUE THREAD

**Issue by CharakaAndaraweera** [viktorstrate/react-mathquill#44]
Can I know whether is there any way to trigger Mathfield.cmd() and Mathfield.focus() functions on an onClick function

**Comment by viktorstrate** [comment]
You would have to store a reference to the mathquill object, using the `mathquillDidMount` prop that you can use in the onClick handler.

Something like this, I haven't tested it though.

```js
const EditableMathExample = () => {
  const [latex, setLatex] = useState('\\frac{1}{\\sqrt{2}}\\cdot 2')
  const mathfield = useRef(null)

  const onClickEvent = () => {
    // use mathfield.cmd() and mathfield.focus() here
  }

  return (
    <div>
      <EditableMathField
        latex={latex}
        mathquillDidMount={mf => {mathfield.current = mf}}
        onChange={(mathField) => {
          setLatex(mathField.latex())
        }}
      />
      <p>{latex}</p>
    </div>
  )
}
```

**Comment by CharakaAndaraweera** [comment]
Thank you very much. It works. Instead of mathfield.cmd(), we have to use mathfield.current.cmd(). Thanks
