### ISSUE TITLE
OnKeyDown support for Editable Math Field

### ISSUE THREAD

**Issue by pramod2** [viktorstrate/react-mathquill#45]
Hi, currently I'm trying to integrate react-mathquill with slatejs editor. I want a keyboard shortcut to toggle editable math field. However, editable math field currently doesn't support onKeyDown. Would it be possible to add it?

**Comment by viktorstrate** [comment]
Take a look at mathquill handlers maybe, which can be passed to the `config` prop.
http://docs.mathquill.com/en/latest/Config/#handlers
