### ISSUE TITLE
Static mathfield inside textarea

### ISSUE THREAD

**Issue by CharakaAndaraweera** [viktorstrate/react-mathquill#46]
Can we add a static mathfield inside a text area?

**Comment by viktorstrate** [comment]
I'm not sure what that would mean. Isn't that just an editable math field?

**Comment by CharakaAndaraweera** [comment]
No. we need to put static mathfield inside a html textarea as a clickable item

**Comment by viktorstrate** [comment]
A static math field is not text, so I don't think that's possible
