### ISSUE TITLE
maxLength, minValue, maxValue support

### ISSUE THREAD

**Issue by amanksingh99** [viktorstrate/react-mathquill#48]
In a component I needed to fix the length of digits to be entered, I have done this on my side slicing the latex but it's not perfect. So I was thinking if it is possible to have maxLength, minValue and maxValue support in EditableMathField just like a <input/> element.

**Comment by viktorstrate** [comment]
I am not sure Mathquill supports that, but take a look at the configuration options http://docs.mathquill.com/en/latest/Config/
