### ISSUE TITLE
Can I set input area width and placeholder?

### ISSUE THREAD

**Issue by syokujinau** [viktorstrate/react-mathquill#5]
as title

**Comment by viktorstrate** [comment]
I have just updated the package to 1.0.9
You should be able to add your own styles to the element like so:

```js
<MathQuill styles={{ width: '250px' }} ... />
```

As for placeholders, I don't think that is supported in Mathquill.
You can however add a starting value with the `latex` prop

**Comment by syokujinau** [comment]
It doesn't seem to work for me.

I tried here
https://stackblitz.com/edit/react-zxxgez

But thank you anyway

**Comment by viktorstrate** [comment]
My bad, it is not `styles` but `style`.
I changed that in your sandbox, and it worked. 😄

**Comment by LennyLip** [comment]
Not work with EditableMathField and StaticMathField

**Comment by viktorstrate** [comment]
@LennyLip it seems to work fine?
https://codesandbox.io/s/nervous-euclid-jjryl?file=/src/App.js

**Comment by LennyLip** [comment]
> @LennyLip it seems to work fine?
> https://codesandbox.io/s/nervous-euclid-jjryl?file=/src/App.js

Sorry, forgot to say, not compile with TypeScript

**Comment by viktorstrate** [comment]
@LennyLip this should be fixed in release `v1.0.1`
