### ISSUE TITLE
Add support for Static Math field

### ISSUE THREAD

**Issue by isaacholt100** [viktorstrate/react-mathquill#9]
Is there a way of rendering a static math field, and if not could this be implemented? It is possible to do this with mathquill: [http://docs.mathquill.com/en/latest/Getting_Started/#static-math-rendering](url). Thanks

**Comment by viktorstrate** [comment]
Thank you for opening the issue.
This is currently not supported in react-mathquill.

I will look into this at some time later next week, when I get some spare time on my hands.

If you, or someone else, want to take on this issue, please write a reply, and I will assign it to you instead.

**Comment by viktorstrate** [comment]
I some time this afternoon to add this. It's added to v0.2.0 on npm

I've updated the readme with instructions.
Also see the new [examples page](https://viktorstrate.github.io/react-mathquill/).
